# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SVvsbz_BvixVvlGBjsMMQ3rweWhHVbwF

Definir la clase Cafetera, la cual abstrae a la entidad susodicha. Diremos que para esta abstracción una cafetera almacenará el café que haga y tendrá una capacidad máxima de tazas.

Por lo tanto, la clase a definir deberá contar con:


--Un atributo que establezca la capacidad máxima de tazas de café que almacenar la cafetera.
--Un atributo que registre la cantidad actual de tazas de café disponibles.
Además, la cafetera deberá contar con ciertos métodos:

..Un método que inicialice una cafetera, indicando cual será su capacidad máxima.

..Implementar el método especial __len__, el cual debe devolver la cantidad actual de tazas de café.

..Un método que permita hacer cierta cantidad de tazas de café, en el cual deberá mostrarse la cantidad de tazas de café que se harán. En caso de haber solicitado hacer una cantidad de tazas que exceda la capacidad de la cafetera, ésta se llenará y luego se mostrará un mensaje indicando este hecho.

..Un método para servir cierta cantidad del café almacenado, en el cual deberá mostrarse la cantidad de tazas de café que se servirán. Si la cantidad de tazas a servir es mayor a la cantidad de tazas almacenadas, entonces se servirá todo el café y se mostrará un mensaje indicando que la cafetera esta vacía.


---------------------Consideraciones---------------------------
La cafetera inicia con vacía.
Si bien en la realidad deben controlarse el nivel de agua y los granos o polvo de café, para este ejercicio no será necesario tomarlo en cuenta. Asumiremos que se gestionan de manera automática.
La clase a implementar y sus métodos deben incluir sus correspondientes docstring.
"""

class Cafetera:
  def __init__(self,capacidad_max,tazas_disponibles):
    self.capacidad_max=capacidad_max
    self.tazas_disponibles=tazas_disponibles
    self.inicializacion=False
    self.cantidad_actual_tazas=0
    self.hacer_cafe=0

  def inicializacion_cafetera(self):
      self.inicializacion=True 
      print("Capacidad maxima:",self.capacidad_max,"Tazas.")

  def cantidad_actual(self):
    self.cantidad_actual_tazas=self.capacidad_max-self.tazas_disponibles
    print("La cantidad de tazas disponibles es de:",self.cantidad_actual_tazas,"tazas de cafe")

  def hacerCafe(self,cantidad_cafe_a_hacer):
    self.hacer_cafe=cantidad_cafe_a_hacer
    if self.cantidad_actual_tazas >= self.hacer_cafe:
     print("Se realizaran:",self.hacer_cafe,"tazas de cafe")
   
cafetera1=Cafetera(20,10)
cafetera1.inicializacion_cafetera()
cafetera1.cantidad_actual()
cafetera1.hacerCafe(5)
