# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10UNrSAS5WhkZn6k_tye-JqsHSAUsAaLI
"""

import random
minNumero=2
maxNumero=12
numRandom=random.randint(minNumero,maxNumero)
jugador1=input()
jugador2=input()
jugador1=int(jugador1)
jugador2=int(jugador2)


if jugador1>numRandom:
  resultado1=jugador1-numRandom
  print(resultado1)

else:
   resultado1=numRandom-jugador1
   print(resultado1)

if jugador2>numRandom:
  resultado2=jugador2-numRandom
  print(resultado2)

else:
   resultado2=numRandom-jugador2
   print(resultado2)

if resultado1<resultado2:
  print("Ganador jugador 1")

elif resultado1>resultado2:
  print("Ganador jugador 2")
else:
  print("empate")

import random
minNumero=2
maxNumero=12
numRandom=random.randint(minNumero,maxNumero)
class Jugadores():
  apuesta1=(input("Jugador 1, Por favor ingrese un numero: "))
  apuesta2=(input("Jugador 2, Por favor ingrese un numero: "))
  apuesta1=int(apuesta1)
  apuesta2=int(apuesta2)
  lanzamiento=False
  numeroRandom=numRandom

  def apuestas(self):
    print("La apuesta del jugador 1 es: ", self.apuesta1,)
    print("La apuesta del jugador 2 es: ", self.apuesta2,)

  def lanzamiento(self,inicio):
    self.lanzamineto=inicio
    if (self.lanzamiento):
      return "Lanzamiento de dados iniciado"
    else:
      return "Esperando el lanzamiento"

  def resultados(self):
    if self.lanzamiento:
      if self.apuesta1 > self.numeroRandom:
        resultado1=self.apuesta1-self.numeroRandom
      else:
        resultado1=self.numeroRandom-self.apuesta1
        
        
      if self.apuesta2 > self.numeroRandom:
        resultado2=self.apuesta2-self.numeroRandom
        
      else:
        resultado2=self.numeroRandom-self.apuesta2
        

      if resultado1<resultado2:
        print("Ganador jugador 1")
 
      elif resultado1>resultado2:
        print("Ganador jugador 2")
      else:
        print("empate")




     
miJugada=Jugadores()
print(miJugada.lanzamiento(True))
miJugada.apuestas()
print("El puntaje de lanzamiento de dados es: ",miJugada.numeroRandom)
miJugada.resultados()