# -*- coding: utf-8 -*-
"""Juego_Dados_random_Con_Input_TERMINADO(Con_Docstring).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/gonarc/EjerciciosPython/blob/main/Juego_Dados_random_Con_Input_TERMINADO(Con_Docstring).ipynb
"""

class Jugadores():

  def __init__(self):
    #clase de las funcionalidades del juego de dados
    self.rondas_a_jugar=0
    self.nombre_jugador1=None
    self.nombre_jugador2=None
    self.lanzar=False
    self.numeroRandom=None
    self.apuesta1=0
    self.apuesta2=0
    self.triunfos_jugador1=0
    self.triunfos_jugador2=0

  def nombre_jugadores(self,nombre1,nombre2):
    #Asignación nombre de jugadores
    self.nombre_jugador1=nombre1
    self.nombre_jugador2=nombre2
    print("Jugaran:","--",self.nombre_jugador1,"VS",self.nombre_jugador2,"--")

  def rondas(self,rondas):
    #Asignación de rondas a jugar
    self.rondas_a_jugar=rondas
    print("SE JUGARAN",self.rondas_a_jugar,"RONDAS.")

  def lanzamiento(self,inicio):
    #Asignación lanzamiento de dado + numero random
    self.lanzar=inicio
    if self.lanzar:
     print("")
     print("")
     import random
     self.numeroRandom=random.randint(2,12)
     print("-- Lanzamiento de dados iniciado --")
     print("")

    else:
      print("Esperando el lanzamiento")

  def apuestas(self,apuesta1,apuesta2):
    #Asignación apuestas de jugador 1 y jugador 2 + muestra en pantalla
        apuesta1=int(apuesta1)
        apuesta2=int(apuesta2)
        self.apuesta1=apuesta1
        self.apuesta2=apuesta2
        print("")
        print("La apuesta de",self.nombre_jugador1,"es:", self.apuesta1)
        print("La apuesta de",self.nombre_jugador2,"es:", self.apuesta2)


  def resultados(self):
    #Muestra en pantalla de resultado de dados
        print("")
        print("El resultado del dado es","--",self.numeroRandom,"--")
        print("")

        if self.numeroRandom == self.apuesta1:
    #Saber si jugador 1 acertó el numero rambom,en caso correcto se le suma punto extra
          self.triunfos_jugador1+=1
          self.triunfos_jugador1 =int(self.triunfos_jugador1)
          print("¡",self.nombre_jugador1.upper(),"ACERTÓ EL NÚMERO !","X2")
        elif self.numeroRandom == self.apuesta2:
    #Saber si jugador 2 acertó el numero rambom,en caso correcto se le suma punto extra
          self.triunfos_jugador2+=1
          self.triunfos_jugador2 =int(self.triunfos_jugador2)
          print("¡",self.nombre_jugador2.upper(),"ACERTÓ EL NÚMERO !","x2")


        if abs(self.numeroRandom-self.apuesta1)<abs(self.numeroRandom - self.apuesta2):
    #Calculo para saber si el jugador 1 está más cerca del resultado que el jugador 2 + muestra en pantalla en caso correcto
            print("--","GANADOR",self.nombre_jugador1.upper(),"--")            
            self.triunfos_jugador1+=1
            self.triunfos_jugador1 =int(self.triunfos_jugador1)

        elif abs(self.numeroRandom-self.apuesta2)<abs(self.numeroRandom - self.apuesta1):
    #Calculo para saber si el jugador 2 está más cerca del resultado que el jugador 1 + muestra en pantalla en caso correcto
            print("--","GANADOR",self.nombre_jugador2.upper(),"--")
            self.triunfos_jugador2+=1
            self.triunfos_jugador2 =int(self.triunfos_jugador2)

        else:
            print("¡EMPATE!")        
        
miJugada=Jugadores()
miJugada.nombre_jugadores(input("Nombre jugador 1: "),input("Nombre jugador 2: "))
miJugada.rondas(int(input("¿Cúantas rondas desea jugar? ")))

while miJugada.triunfos_jugador1 <miJugada.rondas_a_jugar and miJugada.triunfos_jugador2 <miJugada.rondas_a_jugar: 
 miJugada.lanzamiento(True)
 import random
 bot= random.randint(2,12)
 miJugada.apuestas(input(f"{miJugada.nombre_jugador1} ingrese un numero para apostar: "),bot)
 miJugada.resultados()
 print(f"{miJugada.nombre_jugador1} = {miJugada.triunfos_jugador1}  {miJugada.nombre_jugador2} = {miJugada.triunfos_jugador2}")
 print("")
 print("")
 print("")

if miJugada.triunfos_jugador1 > miJugada.triunfos_jugador2:
  print(f"¡ GANADOR FINAL {miJugada.nombre_jugador1.upper()} !")
else:
  print(f"¡ GANADOR FINAL {miJugada.nombre_jugador2.upper()} !")